import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import NavBar from './components/NavBar'
import Aside from './components/Aside'
import Section from './components/Section'
import Dashboard from './components/Dashboard'

export default function Home() {
  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar></NavBar>
      <Aside></Aside>
      <Section></Section>
      <Dashboard></Dashboard>
    </>
  )
}
